update and improve genproject script

diff --git a/genproject b/genproject
--- a/genproject
+++ b/genproject
@@ -2,21 +2,29 @@
 #Helper script for generating my gungeon mod's .csproj file
 
 #Important top level variables
-namespace="CwaffingTheGungy"      #namespace used throughout source code; need to change for my own mod eventually
-projectname="CwaffingTheGungy"    #name of the DLL to create
-projfile="./CwaffingItems.csproj" #the name of the csproj file to generate
+namespace="CwaffingTheGungy"                #namespace used throughout source code; need to change for my own mod eventually
+projectname="CwaffingTheGungy"              #name of the DLL to create
+projfile="./CwaffingItems.csproj"           #the name of the csproj file to generate
+sourcechecksums="./_${namespace}-checksums" #file containing checksums of all source files to determing recompilation
 
 #Easy colors (condensed)
   BLN="\e[0m"   ; UND="\e[1;4m" ; INV="\e[1;7m" ; CRT="\e[1;41m";
   BLK="\e[1;30m"; RED="\e[1;31m"; GRN="\e[1;32m"; YLW="\e[1;33m";
   BLU="\e[1;34m"; MGN="\e[1;35m"; CYN="\e[1;36m"; WHT="\e[1;37m";
 
+
+#Variable tracking if anything actually needs to be rebuild
+rebuild=0
+
+#Array of source files
+sources=()
+
 #Array of items to include in the base project file
 includes=()
 
 #Manually populated includes
 includes+=('<None Include="packages.config" />')
-# includes+=('<Reference Include="System" />')
+includes+=('<Reference Include="System" />') #needed for LinkedList
 # includes+=('<Folder Include="Characters\Acolyte\newspritesetup\custom\" />')
 # includes+=('<Folder Include="Characters\Shade\newspritesetup\custom\" />')
 # includes+=('<Reference Include="Ionic.Zip, Version=1.9.1.8"/>')
@@ -36,6 +44,7 @@ fi
 echo -e "[${GRN}>${BLN}] Scanning for source files"
 while read -r line; do
   includes+=("<Compile Include=\"${line}\" />")
+  sources+=("${line}")
 done <<< $(find "src" -type f -not -path "src/StandardAPI/ItemAPI/Examples/*" -not -path "src/StandardAPI/ItemAPI/FakePrefab/*" -not -path "src/SpriteBuilder.cs" | sed -r 's@/@\\@g')
 
 #Custom Character Embedded resources
@@ -127,7 +136,7 @@ printf "$template" "$namespace" "$projectname" "$replace" | xmllint --format - >
 #Get new checksum of generated csproj file
 newchecksum="$(md5sum "${projfile}.new" | cut -f 1 -d ' ')"
 
-#Compare checksums and clobber the old .csproj file as necessary
+#Compare .csproj checksums and clobber the old .csproj file as necessary
 if [ "$oldchecksum" == "$newchecksum" ]; then
   echo -e "[${GRN}>${BLN}]   No changes to .csproj file!"
   /bin/rm "${projfile}.new"
@@ -135,22 +144,52 @@ else
   echo -e "[${GRN}>${BLN}]   New .csproj file generated, rebuilding project"
   /bin/rm "${projfile}"
   /bin/cp "${projfile}.new" "${projfile}"
+  rebuild=1
 fi
 
-#Don't warn about unused variables (semicolon delimited)
-nowarn="CS0414"
-
-#Finally rebuild the project
-echo -e "[${GRN}>${BLN}] Building project"
-msbuild -noLogo -warnAsMessage:"${nowarn}" -v:minimal -clp:"Summary;Verbosity=minimal"
-
-if [ $? -gt 0 ]; then
-  echo -e "[${RED}@${BLN}] Build failed! D: Check errors above"
-else
-  echo -e "[${GRN}>${BLN}] Build succeeded! :D"
-  if [ $# -gt 0 ] && [ "$1" == "-g" ]; then
-    ./importmod
-    gungy-modded
+#Compare source file checksums to see if we need to rebuild
+if [ $rebuild -eq 0 ]; then
+  echo -e "[${GRN}>${BLN}] Checking if any source files were changed"
+  if [ ! -e "${sourcechecksums}" ]; then
+    echo -e "[${GRN}>${BLN}]   Source checksum file does not exist, rebuilding project"
+    rebuild=1
+  else
+    md5sum --status -c "${sourcechecksums}"
+    if [ $? -gt 0 ]; then
+      echo -e "[${GRN}>${BLN}]   At least one source file was changed, rebuilding project"
+      rebuild=1
+    else
+      echo -e "[${GRN}>${BLN}]   No source files changed, skipping rebuild"
+    fi
   fi
+fi
+
+if [ $rebuild -eq 1 ]; then
+  #Recompute checksums for source file
+  echo -e "[${GRN}>${BLN}] Recomputing source file checksums"
+  /bin/rm -f "${sourcechecksums}"
+  for source in "${sources[@]}"; do
+    s="$(echo "${source}" | sed -re 's@\\@/@g')"
+    echo "$(md5sum "${s}")" >> "${sourcechecksums}"
+  done
+
+  #Don't warn about unused variables (semicolon delimited)
+  nowarn="CS0414"
+
+  #Finally rebuild the project
+  echo -e "[${GRN}>${BLN}] Building project"
+  msbuild -noLogo -warnAsMessage:"${nowarn}" -v:minimal -clp:"Summary;Verbosity=minimal"
+  if [ $? -gt 0 ]; then
+    echo -e "[${RED}@${BLN}] Build failed! D: Check errors above"
+    exit
+  else
+    echo -e "[${GRN}>${BLN}] Build succeeded! :D"
+  fi
+fi
+
+#Launch the game if "-g" flag was passed
+if [ $# -gt 0 ] && [ "$1" == "-g" ]; then
+  ./importmod
+  gungy-modded
 fi
 
